title: "scale_sigm_mul_coef_selection"
backbone:
    name: "iresnet50_normalized"
    learnable: false

scale_predictor:
    name: "MLPHead"
    num_feats: [25088, 512, 1]
    batch_norm: true
    exponent: "relu"
    coefficient: 1.
    fp16: false
