# DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/latex_tables/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - pretty_names@pretty_name.task: task_pretty_name
  - pretty_names@pretty_name.model: model_pretty_name_vMF
  - pretty_names@pretty_name.column: column_pretty_name_unc

# dataset: survFace
dataset: IJBC
#task: open_set_identification
task: unc
#task: verification
#task: closed_set_identification
# CHANGE
metric_table_path: /app/outputs/experiments/new_pipeline_400/${dataset}/open_set_identification/tabels/fractions/0.0333_frac_rejection.csv

caption: >
  Test caption {dataset_name}  {task}.
  
fix_table: True
table_lable: "tab:${task}_${dataset}_unc_metrics"
round_num: 3
use_scriptsize: False
use_adjustbox: False

used_columns: []
used_columns_dict:
  unc:
    IJBB:
      [
        "models",
        "false_ident_num",
        "dir",
        "far",
        "f1",
      ]
    IJBC:
      [
        "models",
        "false_ident_num",
        "dir",
        "far",
        "f1",
      ]
    survFace:
      [
        "models",
        "false_ident_num",
        "dir",
        "far",
        "f1",
      ]
  open_set_identification:
    survFace:
      [
        "pretty_name",
        "final_AUC_5_rank",
        "final_top_5_recall_at_far_0.001",
        #"final_top_5_recall_at_far_1",
      ]
    IJBC:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
    IJBB:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
  verification:
    IJBC:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
    IJBB:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
  closed_set_identification:
    survFace:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_50",
        "final_cmc_at_rank_500",
      ]
    IJBC:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]
    IJBB:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]


sort_models_with: "used_models"
