# DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/latex_tables/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - pretty_names@pretty_name.task: task_pretty_name
  - pretty_names@pretty_name.model: model_pretty_name_nac_unc_dist_search
  - pretty_names@pretty_name.column: column_pretty_name_unc

# dataset: survFace
dataset: IJBC
#task: open_set_identification
task: unc
#task: verification
#task: closed_set_identification
# CHANGE
metric_table_path: /app/experiments/unc_metrics/${dataset}/open_set_identification/open_set_${task}.csv

caption: >
  Исследование методов оценки неопределённости на наборе данных {dataset_name} при решении задачи {task}.
  
fix_table: True
table_lable: "tab:${task}_${dataset}_unc_metrics"
round_num: 3
use_scriptsize: False
use_adjustbox: False

used_columns: []
used_columns_dict:
  unc:
    IJBB:
      [
        "pretty_name",
        "final_auc_1_unc_frac_0.0",
        "final_auc_1_unc_frac_0.2",
        "final_auc_1_unc_frac_0.3",
        "final_auc_1_unc_frac_0.6",
        "final_auc_1_unc_frac_0.7",
      ]
    IJBC:
      [
        "pretty_name",
        "final_auc_1_unc_frac_0.0",
        "final_auc_1_unc_frac_0.2",
        "final_auc_1_unc_frac_0.3",
        "final_auc_1_unc_frac_0.6",
        "final_auc_1_unc_frac_0.7",
      ]
    survFace:
      [
        "pretty_name",
        "final_auc_10_unc_frac_0.0",
        "final_auc_10_unc_frac_0.2",
        "final_auc_10_unc_frac_0.3",
        "final_auc_10_unc_frac_0.6",
        "final_auc_10_unc_frac_0.7",
      ]
  open_set_identification:
    survFace:
      [
        "pretty_name",
        "final_AUC_5_rank",
        "final_top_5_recall_at_far_0.001",
        #"final_top_5_recall_at_far_1",
      ]
    IJBC:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
    IJBB:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
  verification:
    IJBC:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
    IJBB:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
  closed_set_identification:
    survFace:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_50",
        "final_cmc_at_rank_500",
      ]
    IJBC:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]
    IJBB:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]


sort_models_with: "used_models"
