# DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/latex_tables/${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - pretty_names@pretty_name.task: task_pretty_name
  - pretty_names@pretty_name.model: model_pretty_name_vMF
  - pretty_names@pretty_name.column: column_pretty_name_unc
  - meta_data@metric_order: metric_order

# dataset: survFace
dataset: IJBC
# dataset: IJBB
# dataset: whale
#task: open_set_identification
task: filter
#task: verification
#task: closed_set_identification
# CHANGE
metric_table_path: outputs/experiments/paper_v1_tables_power_vmf/open_set_identification/{dataset}/filter_tabels/f1_class_prr_filtering.csv

caption: >
  Prediction Rejection Ration (PRR) of $F_1$ filtering curve on {dataset_name} dataset.
  
fix_table: False
table_lable: "tab:${task}_${dataset}"
round_num: 3
use_scriptsize: True
use_adjustbox: False

used_columns: []
used_columns_dict:
  filter:
    whale:
      [
        "models",
        #"FAR=0.01",
        #"FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
        #"FAR=0.25",
        "FAR=0.3",
      ]
    IJBB:
      [
        "models",
        #"FAR=0.01",
        #"FAR=0.05",
        "FAR=0.1",
        "FAR=0.2",
        #"FAR=0.25",
        "FAR=0.3",
      ]
    IJBC:
      [
        "models",
        "FAR=0.01",
        "FAR=0.05",
        "FAR=0.1",
      ]
  open_set_identification:
    survFace:
      [
        "pretty_name",
        "final_AUC_5_rank",
        "final_top_5_recall_at_far_0.001",
        #"final_top_5_recall_at_far_1",
      ]
    IJBC:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
    IJBB:
      [
        "pretty_name",
        "final_AUC_1_rank",
        "final_top_1_recall_at_far_0.001",
        #"final_top_1_recall_at_far_1",
      ]
  verification:
    IJBC:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
    IJBB:
      [
        "pretty_name",
        "final_auc",
        "final_recall_at_far_1e-06",
        "final_recall_at_far_1e-05",
        #"final_recall_at_far_0.01"
      ]
  closed_set_identification:
    survFace:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_50",
        "final_cmc_at_rank_500",
      ]
    IJBC:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]
    IJBB:
      [
        "pretty_name",
        "final_cmc_at_rank_1",
        "final_cmc_at_rank_10",
        "final_cmc_at_rank_500",
      ]


sort_models_with: "used_models"
