checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/pair_classifiers/01_smart_cos/checkpoints/sota.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
pairs_table_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/metadata_refuse_verification/pairs_1000000_prob_0.5.csv"
config_path: "./configs/models/pair_classifiers/smart_cosine.yaml"
batch_size: 64
distaces_batch_size: 100
uncertainty_strategy: "classifier"
FARs: [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
distance_uncertainty_metrics: ["classifier_classifier", "cosine_classifier", "MLS_classifier", "cosine_harmonic-sum", ]
device_id: 0
save_fig_path: "/beegfs/home/r.kail/faces/figures/test"