checkpoint_path: "/gpfs/gpfs0/k.fedyanin/space/models/pfe/normalized_pfe/sota.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
pairs_table_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/metadata_refuse_verification/pairs_1000000_prob_0.5.csv"
config_path: "./configs/models/iresnet_ms1m_pfe_normalized.yaml"
discriminator_path: "/gpfs/data/gpfs0/k.fedyanin/space/GAN/stylegan.pth"
batch_size: 4
uncertainty_strategy: "GAN"
FARs: [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
distance_uncertainty_metrics: ["cosine_mean", "cosine_harmonic-harmonic", ]
device_id: 0
save_fig_path: "/beegfs/home/r.kail/faces/figures/test"