checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/magface/ms1mv2_ir50_ddp/adapted.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
pairs_table_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/metadata_refuse_verification/pairs_1000000_prob_0.5.csv"
config_path: "./configs/magface/ir50.yaml"
batch_size: 32
uncertainty_strategy: "magface_precalculated"
uncertainty_mode: "confidence"
precalculated_path: "/gpfs/data/gpfs0/k.fedyanin/space/IJB/IJB-C/magface_evaluation/features/1M_pairs/ir100"
distaces_batch_size: 128
FARs: [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
distance_uncertainty_metrics: ["cosine_mean", "cosine_harmonic-harmonic", "cosine_mul", "cosine_squared-sum", "cosine_squared-harmonic", ]
device_id: 0
save_fig_path: "/trinity/home/r.kail/faces/figures/test"