checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/pfe/normalized_pfe/sota.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
pairs_table_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/metadata_refuse_verification/pairs_1000_prob_0.1.csv"
config_path: "./configs/models/iresnet_ms1m_pfe_normalized.yaml"
batch_size: 16
uncertainty_strategy: "head"
uncertainty_mode: "uncertainty"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
distance_uncertainty_metrics: ["cosine_mean", "cosine_harmonic-sum", "cosine_harmonic-harmonic", "MLS_harmonic-sum", "MLS_harmonic-harmonic", ]
device_id: 0
save_fig_path: "/beegfs/home/r.kail/faces/figures/test"