# pytorch_lightning==2.0.0
seed_everything: 777
trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: null
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: scf-uniform-batch
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      job_type: null
      config: null
      entity: null
      reinit: null
      tags: null
      group: null
      notes: null
      magic: null
      config_exclude_keys: null
      config_include_keys: null
      mode: null
      allow_val_change: null
      resume: null
      force: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      save_code: null
      fork_from: null
      settings: null
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      dirpath: outputs/scf_uniform_batch/default_scf
      filename: null
      monitor: null
      verbose: false
      save_last: true
      save_top_k: 1
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: 1
      save_on_train_epoch_end: null
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: face_lib.models.scf.Prediction_writer
    init_args:
      output_dir: /app/cache/features
      file_name: ms1m_emb
      write_interval: epoch
  fast_dev_run: false
  max_epochs: 16
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  enable_checkpointing: true
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: outputs/scf_train
ckpt_path: /app/model_weights/scf_base.ckpt
model:
  class_path: face_lib.models.SphereConfidenceFace
  init_args:
    backbone:
      class_path: face_lib.models.lightning_wrappers.ResNet
      init_args:
        resnet_name: iresnet50_normalized
        weights: /app/model_weights/backbone/ms1mv3_arcface_r50/backbone.pth
        learnable: false
    head:
      class_path: face_lib.models.heads.SCFHead
      init_args:
        convf_dim: 25088
        latent_vector_size: 2048
    scf_loss:
      class_path: face_lib.models.losses.KLDiracVMF
      init_args:
        z_dim: 512
        radius: 64
    optimizer_params:
      optimizer_path: torch.optim
      optimizer_name: AdamW
      params:
        lr: 3.0e-05
        weight_decay: 0.0005
    scheduler_params:
      scheduler: StepLR
      params:
        step_size: 2
        gamma: 0.5
      interval: step
      frequency: 1
    permute_batch: false
    softmax_weights:
      class_path: face_lib.models.scf.SoftmaxWeights
      init_args:
        softmax_weights_path: /app/model_weights/backbone/ms1mv3_arcface_r50/softmax_weight.pt
        radius: 64
    validation_dataset:
      class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
      init_args:
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: true
    template_pooling_strategy:
      class_path: evaluation.template_pooling_strategies.PoolingConcentration
    recognition_method:
      class_path: evaluation.verification_methods.distance_based_verification.VerifEval
      init_args:
        distance_function:
          class_path: evaluation.distance_functions.distance_functions.CosineSimPairwise
    verification_metrics:
    - _target_: evaluation.metrics.TarFar
      far_range:
      - -6
      - -0.5
      - 0.1
      display_fars:
      - 1.0e-06
      - 1.0e-05
      - 0.0001
      - 0.001
data:
  class_path: face_lib.dataset_classes.lightning_datasets.UncertaintyDataModule
  init_args:
    train_dataset:
      class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
      init_args:
        root_dir: /app/datasets/ms1m/
        test: false
        num_classes: 0
        album_augments: null
        album_probability: 0.0
    validation_dataset:
      class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
      init_args:
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: true
    predict_dataset:
      class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
      init_args:
        root_dir: /app/datasets/ms1m/
        test: false
        num_classes: 0
        album_augments: null
        album_probability: 0.0
    batch_size: 400
    num_workers: 36
    train_batch_sampler:
      class_path: face_lib.dataset_classes.samplers.UniformBatchSampler
      init_args:
        cosine_sim_path: /app/model_weights/ms1m_cache/cosine_sim.npy
        batch_size: 400
