# INNER PARAMETERS DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/uncertainty_benchmark/uncertainty_benchmark_${now:%Y-%m-%d_%H-%M-%S}


# DEFAULT PARAMETERS

template_datasets:
  pfe_default:
    class_path: face_lib.models.lightning_resnet.ResNet
    init_args:
      dataset_path: "/app/data/big"
      protocol_path: "/app/data/test1"
      features_path: /app/cache/features/PFE_features.pickle
      uncertainty_path: /app/cache/features/PFE_uncertainty.pickle
      