hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}

use_two_galleries: True
recompute_template_pooling: False
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]

test_dataset:
  _target_: evaluation.test_datasets.FaceRecogntioniDataset
  dataset_name: survFace
  dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

# test_dataset:
#   _target_: evaluation.test_datasets.FaceRecogntioniDataset
#   dataset_name: IJBB
#   dataset_path: /app/datasets/arcface_ijb/IJBB

open_set_identification_methods:

  # - evaluation_1N_function: 
  #     _target_: evaluation.eval_functions.CosineSim
  #     confidence_function: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #       foo: bar
  #   embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_and_scf_score.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 0
      cosine_pred: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_and_scf_shift_0_score.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 150
      cosine_pred: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_and_scf_shift_200_score.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 300
      cosine_pred: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_and_scf_shift_300_score.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 600
      cosine_pred: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_and_scf_shift_600_score.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 1200
      cosine_pred: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_and_scf_shift_1200_score.npz"
