name: "accuracy_lfw_6000_pairs"
type: "lfw"
lfw_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/data_aligned_sphereface_repo"
lfw_pairs_txt_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/ldmarks.txt"
N: 6000
n_folds: 10
