name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch::pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch::torchvision=0.11.3=py39_cu113
  - cudatoolkit=11.3.1
  - psutil
  - python=3.9.7
  - pip=21.2.4
  - openblas-devel
  - tqdm
  - nose
  - cython
  - pysoundfile
  - pip:
    - progressbar2
    - exman~=0.1.9
    - torch~=1.8.0
    - easydict~=1.9
    - opencv-python~=4.5.1.48
    - mxnet~=1.6.0
    - numpy~=1.20.1
    - PyYAML~=5.4.1
    - scipy~=1.6.1
    - pandas~=1.2.3
    - torchvision~=0.9.0
    - scikit-learn~=0.24.1
    - tqdm~=4.59.0
    - imageio~=2.9.0
    - matplotlib~=3.3.4
    - seaborn~=0.11.1