name: base
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - psutil
  - python=3.9.7
  - conda-forge::scikit-image
  - conda-forge::termcolor
  - conda-forge::tensorboard
  - conda-forge::black
  - conda-forge::hydra-core
  - conda-forge::numexpr
  - anaconda::ipython
  - anaconda::path
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - pysoundfile
  - pip:
    - scikit-learn-intelex
    - numexpr
    - wandb
    - onnx
    - onnx2torch
    - albumentations
    - tabulate
    - onnxruntime-gpu
    - glob2
    - jsonargparse[signatures]
    - torchvision
    - progressbar2
    - exman~=0.1.9
    - easydict~=1.9
    - pytorch-lightning==2.0.0
    - opencv-python~=4.5.1.48
    - mxnet-mkl==1.6.0
    - bcolz-zipline
    - "dask[array]"
    - botorch
    - numpy==1.23.1
    - PyYAML~=5.4.1
    - scipy
    - pandas~=1.2.3
    - scikit-learn~=0.24.1
    - tqdm~=4.59.0
    - imageio~=2.9.0
    - matplotlib~=3.3.4
    - seaborn~=0.11.1
    - scikit-learn-intelex
    - "black[jupyter]"
    - geotorch