# INNER PARAMETERS DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/${hydra.job.name}/${hydra.job.name}_${now:%Y-%m-%d_%H-%M-%S}

# DEFAULT PARAMETERS

dataset_path: "/app/data/big"
protocol: "ijbc"
protocol_path: "/app/data/test1"
batch_size: 64
distaces_batch_size: 8
uncertainty_strategy: "head"
uncertainty_mode: "confidence"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
device_id: 0
equal_uncertainty_enroll: True
verbose: True


# CHANGE THESE PARAMETERS

checkpoint_path: "/app/data/pfe.pth"
config_path: "/app/configs/models/iresnet_ms1m_pfe_normalized.yaml"

fusion_distance_uncertainty_metrics: ["PFE_cosine_prob-unc", ]
cache_dir: "/app/cache"


