# INNER PARAMETERS DO NOT CHANGE
hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/template_reject_verification/template_reject_verification_${now:%Y-%m-%d_%H-%M-%S}

# DEFAULT PARAMETERS

dataset_path: "/app/data/big"
protocol: "ijbc"
protocol_path: "/app/data/test1"
batch_size: 64
distaces_batch_size: False
uncertainty_strategy: "head"
uncertainty_mode: "confidence"
FARs: [0.0001] #, 0.001, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 50]
device_id: 0
equal_uncertainty_enroll: True
verbose: True


# CHANGE THESE PARAMETERS
debug: False


cache_dir: "/app/cache"
checkpoint_path: "/app/data/pfe.pth"
config_path: "/app/configs/models/iresnet_ms1m_pfe_normalized.yaml"
norm_mean: True
methods:

  - fusion_name: PFE
    distance_name: cosine
    uncertainty_name: prob-unc
    uncertainty_mode: confidence
    likelihood:
      name: DefaultPfeFast
      args:
        T: 1
        sigma_shift: 0
  - fusion_name: PFE
    distance_name: cosine
    uncertainty_name: prob-unc
    uncertainty_mode: confidence
    likelihood:
      name: DefaultPfeFast
      args:
        T: 1
        sigma_shift: 0.001
  - fusion_name: PFE
    distance_name: cosine
    uncertainty_name: prob-unc
    uncertainty_mode: confidence
    likelihood:
      name: DefaultPfeFast
      args:
        T: 1
        sigma_shift: 0.01
  - fusion_name: PFE
    distance_name: cosine
    uncertainty_name: prob-unc
    uncertainty_mode: confidence
    likelihood:
      name: DefaultPfeFast
      args:
        T: 1
        sigma_shift: 0.1
  - fusion_name: PFE
    distance_name: cosine
    uncertainty_name: prob-unc
    uncertainty_mode: confidence
    likelihood: 
      name: CosineDistance
      args:
        T: 1





