

seed_everything: true
trainer:
  logger: dvclive.lightning.DVCLiveLogger
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      dirpath: outputs/models
  max_epochs: 30
  accelerator: gpu
model:
    backbone:
        class_path: face_lib.model.lightning_resnet.ResNet
        init_args:
            resnet_name: iresnet50_normalized
            weights: /app/data/models/backbone/ms1mv3_arcface_r50/backbone.pth
            learnable: False
    head:
        class_path: face_lib.model.heads.SCFHead
        init_args:
            convf_dim: 25088
    scf_loss:
        class_path: face_lib.model.losses.KLDiracVMF
        init_args:
            z_dim: 512
            radius: ${model.radius}
    optimizer_params:
        optimizer: Adam
        params:
            lr: 3e-5
            weight_decay: 5e-4
    scheduler_params:
        scheduler: StepLR
        params:
            step_size: 2
            gamma: 0.5
    softmax_weights_path: /app/data/models/backbone/ms1mv3_arcface_r50/softmax_weight.pt
    radius: 64

data:
    class_path: face_lib.datasets.lightning_ms1m.MS1M
    init_args:
        data_ms1m_dir: /app/data/ms1m/
        batch_size: 64





#
title: "iresnet_ms1m_pfe_normalized"
backbone:
    name: "iresnet50_normalized"
    learnable: false
head:
    name: "pfe_head_adjustable"
    in_feat: 25088
    out_feat: 512
    learnable: true
    criterion:
        name: "mlsloss"
        mean: false
optimizer:
    name: "sgd"
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
scheduler:
    name: "multistep_lr"
    milestones: [3, 6, 9]
    gamma: 0.1
dataset:
    name: "ms1m"
    path: "/app/data/ms1m/"
    batch_size: 64
    num_face_pb: 4
pretrained_backbone: /app/data/models/backbone/ms1mv3_arcface_r50/backbone.pth
batch_size: 256
num_classes_batch: 4
is_distributed: true
iterations: 2000
epochs: 12
path_list: /app/data/casia/list_data.txt
in_size: [112, 112]
logging:
    print_freq: 10
    save_freq: 1
evaluation_configs:
    - name: "lfw_dilemma"
      type: "lfw"
      lfw_path: "/app/data/lfw/data_aligned_sphereface_repo"
    - name: "low_high_similarity"
      type: "lfw"
      lfw_path: "/app/data/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/app/data/lfw/ldmarks.txt"
    - name: "lfw_6000_pairs"
      type: "lfw"
      lfw_path: "/app/data/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/app/data/lfw/pairs_val_6000.txt"
      N: 6000
      n_folds: 10
