

seed_everything: 7
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: "face_incertainty_train"
  log_every_n_steps: 3
  default_root_dir: outputs/scf_train
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      every_n_train_steps: 1000
      dirpath: outputs/scf_train/weights_nose
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args: 
      logging_interval: "step"
  - class_path: face_lib.models.scf.IJB_writer
    init_args: 
      output_dir: /app/cache/features
      subset: ${data.init_args.data_predict_subset}
      write_interval: epoch
  max_epochs: 5
  accelerator: gpu
  devices: 2
model:
    class_path: face_lib.models.scf.SphereConfidenceFace
    init_args:
        backbone:
            class_path: face_lib.models.lightning_wrappers.ResNet
            init_args:
                resnet_name: iresnet50_normalized
                weights: /app/model_weights/backbone/ms1mv3_arcface_r50/backbone.pth
                learnable: False
        head:
            class_path: face_lib.models.heads.SCFHead
            init_args:
                convf_dim: 25088
                latent_vector_size: 2048
        scf_loss:
            class_path: face_lib.models.losses.KLDiracVMF
            init_args:
                z_dim: 512
                radius: 64
        softmax_weights:
            class_path: face_lib.models.scf.SoftmaxWeights
            init_args:
                softmax_weights_path: /app/model_weights/backbone/ms1mv3_arcface_r50/softmax_weight.pt
                radius: 64 #${model.scf_loss.init_args.radius}
        optimizer_params:
            optimizer_path: face_lib.optimizers.lars
            optimizer_name: LARS
            params:
                lr: 0.15 #= 0.3 × BatchSize/256
                weight_decay: 1e-6
        scheduler_params:
            scheduler: StepLR
            params:
                step_size: 5000
                gamma: 0.5
            interval: "step"
            frequency: 1
        # scheduler_params:
        #     scheduler: CosineAnnealingWarmRestarts
        #     params:
        #         T_0: 5000
        #         eta_min: 3e-8


data:
    class_path: face_lib.datasets.lightning_datasets.UncertaintyDataModule
    init_args:
        data_train_dir: /app/datasets/ms1m/
        add_nose: False
        data_predict_dir: /app/datasets/arcface_ijb
        data_predict_subset: IJBC
        batch_size: 128
        num_workers: 20

