checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/pfe/normalized_pfe/sota.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
protocol_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/IJB-C/protocols/archive"
config_path: "./configs/models/iresnet_ms1m_pfe_normalized.yaml"
uncertainty_strategy: "head"
protocol: "ijbc"
fusion_distance_methods: ["softmax-100_cosine", "softmax-200_cosine", "softmax-300_cosine", "softmax-500_cosine", "softmax-700_cosine", "softmax-1000_cosine", "softmax-1500_cosine", ]
FARs: [1e-05, 5e-05, 0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, ]
device_id: 0
batch_size: 64
save_table_path: "/beegfs/home/r.kail/faces/figures/test/table.pkl"
verbose: True