title: "iresnet_ms1m_pair_classifier_smart_cosine"
backbone:
    name: "iresnet50_normalized"
    learnable: false

scale_predictor:
    name: "MLPHead"
    num_feats: [25088, 512, 1]
    batch_norm: true
    activation: "sigm_mul"
    fp16: false
