hydra:
  run:
    dir: ${exp_dir}

exp_dir: outputs/experiments/simple_mc
use_two_galleries: False
recompute_template_pooling: True
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name_unc.yaml
create_pool_plot: False

test_datasets:
  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: ms1m
  #   dataset_path: /app/datasets/ms1m_ident

  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: IJBB
  #   dataset_path: /app/datasets/arcface_ijb/IJBB

  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: IJBC
    dataset_path: /app/datasets/arcface_ijb/IJBC

  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: lfw
  #   dataset_path: /app/datasets/lfw_ident


  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set



open_set_identification_metrics:
  # - _target_: evaluation.metrics.FrrFarIdent
  - _target_: evaluation.metrics.DirFar
  # - _target_: evaluation.metrics.F1

fractions: [0, 0.3, 15]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.DirFar

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1_classic



default_beta: 0.5



far_list: 0.1 # for now
# far_list:
#   - 0.05

# # IJBC
# tau_list: 
# #  - 0.3316050800917002 # far 0.1
#  - 0.3544668614198186 # far 0.05
# #  - 0.41305037376834797 # far 0.01
# #  - 0.4344078641808415 # far 0.005

# # IJB-B

# # tau_list: 
# #   # - 0.3122234142166135 # far 0.1
# #   # - 0.3433289481793866 # far 0.05
# #   - 0.4491698259631683 # far 0.01
# #   # - 0.7189225782977178 # far 0.005

# # LFW
# # tau_list: 
# #   - 0.29610780254648883 # far 0.1
# #   - 0.3151530824027877 # far 0.05
# #   - 0.3576923759220011 # far 0.01
# #   - 0.3759362888911925 # far 0.005

# tau_to_far:
#   IJBC:
#     0.3316050800917002: 0.1
#     0.3544668614198186: 0.05
#     0.41305037376834797: 0.01
#     0.4344078641808415: 0.005
#   IJBB:
#     0.3122234142166135: 0.1
#     0.3433289481793866: 0.05
#     0.4491698259631683: 0.01
#     0.7189225782977178: 0.005
#   lfw:
#     0.29610780254648883:  0.1
#     0.3151530824027877 : 0.05
#     0.3576923759220011 : 0.01
#     0.3759362888911925 : 0.005


open_set_identification_methods:

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  #PoolingConcentration, PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.class_prob_models.MonteCarloPredictiveProb
      M: 50
      gallery_prior: power
      emb_unc_model: vMF
      beta: 0.5
      far: ${far_list}
    pretty_name: "$u_{MC}$ simple"


  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault  #PoolingConcentration, PoolingDefault
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
    use_detector_score: False
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      distance_function: 
        _target_: evaluation.distance_functions.open_set_identification.CosineSim
      class_model: power
      far: ${far_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 1 # when 1, only scf unc is used
      aggregation: sum
      T: 1
      T_data_unc: 1
    pretty_name: "$u_{SCF}$"


  # - embeddings: power_noise_v3
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault      #PoolingConcentration
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingDefault #PoolingProb
  #   use_detector_score: False
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     distance_function: 
  #       _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #     class_model: power
  #     far: ${far_list}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 1 # when 1, only scf unc is used
  #     aggregation: sum
  #     T: 1
  #     T_data_unc: 1
  #   pretty_name: "$u_{noise}$"

