hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
use_two_galleries: True
recompute_template_pooling: False
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]
open_set_recognition_methods:

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SVM
      use_unc: True
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_unc_SVM_det_and_scf_score.npz"
    
  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.scf.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
      k_shift: 150
      use_cosine_sim_match: False
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_SCF_det_and_scf_score_shift_150_scf_dist.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_and_scf_score_.npz"

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.SVM
      use_unc: False
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_basic_SVM_det_and_scf_score.npz"
