hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}

restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
batch_size: 16
save_result: "/app/outputs/IJB_result/${subset}_${open_set_identification_method}.npz"
is_one_2_N: True  # Run 1:N test instead of 1
# evaluation_1N_function: 
#   class_path: evaluation.one_to_N_eval_functions.PairwiseSims
#   init_args:
#     foo: bar
open_set_identification_method: TcmNN
evaluation_1N_function: 
  class_path: evaluation.one_to_N_eval_functions.${open_set_identification_method}
  init_args:
    number_of_nearest_neighbors: 2
    scale: 2
    p_value_cache_path: /app/cache/tcmNN_cache