hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
use_two_galleries: True
recompute_template_pooling: False
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]
open_set_recognition_methods:
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: True
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_and_pfe_score_.npz"
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: True
    features: pfe
    use_detector_score: False
    save_result: "${exp_dir}/${subset}_CosineSim_pfe_score_.npz"
    
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: True
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_and_scf_score_.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: False
    features: scf
    use_detector_score: False
    save_result: "${exp_dir}/${subset}_CosineSim.npz"
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: False
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_score.npz"
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    aggregate_gallery_templates_with_confidence: True
    features: scf
    use_detector_score: False
    save_result: "${exp_dir}/${subset}_CosineSim_scf_score.npz"



  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.SCF
  #     init_args:
  #       confidence_function: 
  #         class_name: MaxSimilarity_confidence
  #         init_args:
  #           foo: bar
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   aggregate_gallery_templates_with_confidence: False
  #   save_result: "${exp_dir}/${subset}_SCF.npz"
    
  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.SCF
  #     init_args:
  #       confidence_function: 
  #         class_name: NAC_confidence
  #         init_args:
  #           k: 16
  #           s: 1
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   aggregate_gallery_templates_with_confidence: False
  #   save_result: "${exp_dir}/${subset}_SCF_NAC.npz"




  
  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.TcmNN
  #     init_args:
  #       number_of_nearest_neighbors: 50
  #       scale: 1
  #       p_value_cache_path: /app/cache/tcmNN_cache
  #   save_result: "${exp_dir}/${subset}_TcmNN.npz"
