hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}

restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1

open_set_recognition_methods:
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PairwiseSims
      init_args:
        psr_top_k: 0 # https://ieeexplore.ieee.org/document/1512050
        use_entropy: False
    save_result: "/app/outputs/IJB_result/${subset}_PairwiseSims.npz"
  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.PairwiseSims
  #     init_args:
  #       psr_top_k: 10
  #       use_entropy: False
  #   save_result: "/app/outputs/IJB_result/${subset}_PairwiseSims_withPSR_10.npz"
  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.PairwiseSims
  #     init_args:
  #       psr_top_k: 1000
  #       use_entropy: False
  #   save_result: "/app/outputs/IJB_result/${subset}_PairwiseSims_withPSR_1000.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PairwiseSims
      init_args:
        psr_top_k: 0
        use_entropy: True
    save_result: "/app/outputs/IJB_result/${subset}_PairwiseSims_entropy.npz"


  
  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.TcmNN
  #     init_args:
  #       number_of_nearest_neighbors: 50
  #       scale: 1
  #       p_value_cache_path: /app/cache/tcmNN_cache
  #   save_result: "/app/outputs/IJB_result/${subset}_TcmNN.npz"
