hydra:
  run:
    dir: ${exp_dir}

exp_dir: experiments/unified_osr

use_two_galleries: True
recompute_template_pooling: False

test_dataset:
  _target_: evaluation.test_datasets.FaceRecogntioniDataset
  dataset_name: survFace
  dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

# test_dataset:
#   _target_: evaluation.test_datasets.FaceRecogntioniDataset
#   dataset_name: IJBB
#   dataset_path: /app/datasets/arcface_ijb/IJBB

open_set_identification_metrics:
  - _target_: evaluation.metrics.DetectionAndIdentificationRate
    top_n_ranks: [1, 5, 10, 20]
    far_range: [-4, 0, 100]
    display_fars: [0.0001, 0.001, 0.01, 0.1, 1]

closed_set_identification_metrics:
  - _target_: evaluation.metrics.CMC
    top_n_ranks: [1, 2, 3, 5, 10, 20, 50, 100, 500, 1000]
    display_ranks: [1, 5, 10, 50, 100, 500, 1000]

verification_metrics:
  - _target_: evaluation.metrics.TarFar
    far_range: [-6, 0, 100]
    display_fars: [0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1]

# open_set_uncertainty_metrics:
  # - _target_: evaluation.metrics.MeanDistanceReject
  #   fractions: [0, 0.55, 0.01]
  #   with_unc: False
  #   metric_to_monitor:
  #     _target_: evaluation.metrics.DetectionAndIdentificationRate
  #     top_n_ranks: [1, 10, 20]
  #     far_range: [-4, 0, 100] 
  #     display_fars: [0.0001, 0.001, 0.01, 0.1, 1]


open_set_identification_methods:
  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Косинусный MaxProb"
  
  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 100
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=100"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 150
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=150"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 175
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=175"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 200
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=200"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 275
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=275"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 300
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=300"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 350
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=350"
  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MisesProb
        kappa: 375
        beta: 0.5
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    pretty_name: "Uniform prob conf kappa=375"
