hydra:
  run:
    dir: ${exp_dir}

exp_dir: outputs/experiments/vmf_pool_${default_kappa}
use_two_galleries: True
recompute_template_pooling: True
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name_unc.yaml


test_datasets:
  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: ms1m
  #   dataset_path: /app/datasets/ms1m_ident

  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: IJBC
    dataset_path: /app/datasets/arcface_ijb/IJBC

  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: IJBB
  #   dataset_path: /app/datasets/arcface_ijb/IJBB
  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set



open_set_identification_metrics:
  # - _target_: evaluation.metrics.FrrFarIdent
  - _target_: evaluation.metrics.DirFar
  # - _target_: evaluation.metrics.F1

fractions: [0, 0.3, 15]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.DirFar

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1



default_kappa: 400
default_beta: 0.5
open_set_identification_methods:

  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingProb
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 1
  #     aggregation: sum
  #     process_unc: prob
  #     T: 5.3757
  #     T_data_unc: 1
  #   pretty_name: "SCF pool"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingProb
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      aggregation: sum
      process_unc: prob
      T: 5.3757
      T_data_unc: 30
    pretty_name: "vmf pool"


  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingProb
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     aggregation: sum
  #     process_unc: prob
  #     T: 5.3757
  #     T_data_unc: 1
  #   pretty_name: "VMF pool"


  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     aggregation: sum
  #     process_unc: prob
  #     T: 5.3757
  #     T_data_unc: 1
  #   pretty_name: "vMF_T-5.3757"

