hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
use_two_galleries: True
recompute_template_pooling: False
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]
open_set_identification_methods:

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.CosineSim
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_and_harmonic_pfe_score.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1.2
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1.2_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1.5
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1.5_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1.6
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1.6_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1.7
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1.7_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 1.8
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_1.8_pfe_dist.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.PFE
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        use_cosine_sim_match: False
        variance_scale: 2
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_PFE_harmonic_mean
    restore_embs: /app/cache/features/pfe_ijb_embs_${subset}.npz
    features: pfe
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_PFE_det_and_harmonic_pfe_score_var_scale_2_pfe_dist.npz"
