hydra:
  run:
    dir: ${exp_dir}
#exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}
exp_dir: outputs/experiments/pooling_methods

use_two_galleries: True
recompute_template_pooling: False

# test_dataset:
#   _target_: evaluation.test_datasets.FaceRecogntioniDataset
#   dataset_name: survFace
#   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

test_dataset:
  _target_: evaluation.test_datasets.FaceRecogntioniDataset
  dataset_name: IJBC
  dataset_path: /app/datasets/arcface_ijb/IJBC

open_set_identification_metrics:
  - _target_: evaluation.metrics.DetectionAndIdentificationRate
    top_n_ranks: [1, 10, 20]
    far_range: [-4, 0, 100]

closed_set_identification_metrics:
  - _target_: evaluation.metrics.CMC
    top_n_ranks: [1, 2, 3, 5, 10, 20, 50, 100]

verification_metrics:
  - _target_: evaluation.metrics.TarFar
    far_range: [-5, 0, 100]

open_set_uncertainty_metrics:
  - _target_: evaluation.metrics.MeanDistanceReject
    metric_to_monitor:
      _target_: evaluation.metrics.DetectionAndIdentificationRate
      top_n_ranks: [1, 10, 20]
      far_range: [-4, 0, 100] 



closed_set_identification_methods:
  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_scf_score.npz"


verification_methods:
  - evaluation_function:
      _target_: evaluation.eval_functions.verification.distance_based_evaluation.VerifEval
      distance_function:
        _target_: evaluation.eval_functions.distaince_functions.PfeSimPairwise
        variance_scale: 1
    embeddings_path: ${test_dataset.dataset_path}/embeddings/pfe_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingPFEHarmonicMean
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_pfe_det_and_pfe_score.npz"

  # - evaluation_function:
  #     _target_: evaluation.eval_functions.verification.distance_based_evaluation.VerifEval
  #     distance_function:
  #       _target_: evaluation.eval_functions.distaince_functions.ScfSimPairwise
  #       k_shift: 0
  #   embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${test_dataset.dataset_name}_scf_det_and_scf_score.npz"

  # - evaluation_function:
  #     _target_: evaluation.eval_functions.verification.distance_based_evaluation.VerifEval
  #     distance_function:
  #       _target_: evaluation.eval_functions.distaince_functions.CosineSimPairwise
  #   embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_and_scf_score.npz"



open_set_identification_methods:
  # - evaluation_function: 
  #     _target_: evaluation.eval_functions.open_set_identification.PFE
  #     confidence_function: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     variance_scale: 1
  #     use_cosine_sim_match: False
  #   embeddings_path: ${test_dataset.dataset_path}/embeddings/pfe_embs_${test_dataset.dataset_name}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingPFEHarmonicMean
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${test_dataset.dataset_name}_PFE_det_and_pfe_score.npz"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.SCF
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      k_shift: 0
      use_cosine_sim_match: False
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_SCF_det_and_scf_score.npz"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_scf_score.npz"



 
