hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
use_two_galleries: True
recompute_template_pooling: False
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]
open_set_recognition_methods:

  # - evaluation_1N_function: 
  #     class_path: evaluation.one_to_N_eval_functions.CosineSim
  #     init_args:
  #       confidence_function: 
  #         class_name: MaxSimilarity_confidence
  #         init_args:
  #           foo: bar
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   template_pooling_strategy:
  #     function_path: evaluation.template_pooling_strategies.pooling_SCF
  #   features: scf
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${subset}_CosineSim_det_and_scf_score.npz"

  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.SCF
      init_args:
        confidence_function: 
          class_name: NAC_confidence
          init_args:
            k: 15
            s: 1
            shift: 0
            normalize: True
        k_shift: 150
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_SCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_SCF_NAC_det_and_scf_score_shift_150.npz"
 
  - evaluation_1N_function: 
      class_path: evaluation.one_to_N_eval_functions.SCF
      init_args:
        confidence_function: 
          class_name: MaxSimilarity_confidence
          init_args:
            foo: bar
        k_shift: 150
    restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
    template_pooling_strategy:
      function_path: evaluation.template_pooling_strategies.pooling_SCF
    features: scf
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_SCF_det_and_scf_score_shift_150.npz"

 