hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
subset: IJBC # Subset test target, could be IJBB / IJBC
use_two_galleries: True
recompute_template_pooling: True
batch_size: 16
is_one_2_N: True  # Run 1:N test instead of 1
far_range: [-4, 0, 100]

test_dataset:
  _target_: evaluation.test_datasets.FaceRecogntioniDataset
  dataset_name: IJBB
  dataset_path: /app/datasets/arcface_ijb/IJBB

open_set_recognition_methods:

  - evaluation_1N_function: 
      _target_: evaluation.eval_functions.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
        foo: bar
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_ijb_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${subset}_CosineSim_det_and_scf_score.npz"

