hydra:
  run:
    dir: ${exp_dir}
#exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}
exp_dir: outputs/experiments/pooling_methods

use_two_galleries: True
recompute_template_pooling: False
open_set_ident_far_range: [-4, 0, 100]
varif_far_range: [-5, 0, 100]
# test_dataset:
#   _target_: evaluation.test_datasets.FaceRecogntioniDataset
#   dataset_name: survFace
#   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

test_dataset:
  _target_: evaluation.test_datasets.FaceRecogntioniDataset
  dataset_name: IJBC
  dataset_path: /app/datasets/arcface_ijb/IJBC

open_set_identification_metrics:
  - _target_: evaluation.metrics.DetectionAndIdentificationRate
    top_n_ranks: [1, 10, 20]

closed_set_identification_metrics:
  - _target_: evaluation.metrics.DetectionAndIdentificationRate
    top_n_ranks: [1, 10, 20]

verification_metrics:
  - _target_: evaluation.metrics.TarFar


verification_methods:
  - evaluation_function:
      _target_: evaluation.eval_functions.verification.distance_based_evaluation.VerifEval
      distance_function:
        _target_: evaluation.eval_functions.distaince_functions.CosineSimPairwise
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_and_scf_score.npz"

open_set_identification_methods:
  # - evaluation_function: 
  #     _target_: evaluation.eval_functions.open_set_identification.SCF
  #     confidence_function: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     k_shift: 0
  #     use_cosine_sim_match: False
  #   embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_and_scf_score.npz"

  - evaluation_function: 
      _target_: evaluation.eval_functions.open_set_identification.CosineSim
      confidence_function: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
    embeddings_path: ${test_dataset.dataset_path}/embeddings/scf_embs_${test_dataset.dataset_name}.npz
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    save_result: "${exp_dir}/${test_dataset.dataset_name}_CosineSim_det_score.npz"



 
