hydra:
  run:
    dir: ${exp_dir}
exp_dir: outputs/ijb_evals/ijb_evals_${now:%Y-%m-%d_%H-%M-%S}


metrics:
  - _target_: evaluation.metrics.DIRFAR
    far_range: [-4, 0, 100]
  - _target_: evaluation.metrics.RejectAUROC
    xs_range: [0, 1, 100]

open_set_recognition_methods:
  - similarity_function: 
      _target_: evaluation.similarity_functions.CosineSim
    confidence_function:
      _target_: evaluation.confidence_functions.MaxSimilarity_confidence
    dataloader:
      _target_: evaluation.dataloaders.DataLoader1N
      use_two_galleries: True
      subset: IJBC
      data_path: datasets/arcface_ijb/ # Dataset path containing IJBB and IJBC sub folder
      features: scf
      use_detector_score: True
      template_pooling:
        _target_: evaluation.template_pooling_strategies.PoolingSCF
  # - evaluation_1N_function: 
  #     _target_: evaluation.eval_functions.scf.SCF
  #     confidence_function: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #       foo: bar
  #     k_shift: 150
  #     use_cosine_sim_match: False
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   features: scf
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${subset}_SCF_det_and_scf_score_shift_150_scf_dist.npz"

  # - evaluation_1N_function: 
  #     _target_: evaluation.eval_functions.CosineSim
  #     confidence_function: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #       foo: bar
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   features: scf
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${subset}_CosineSim_det_and_scf_score_.npz"

  # - evaluation_1N_function: 
  #     _target_: evaluation.eval_functions.SVM
  #     use_unc: False
  #     C: 1
  #     loss: squared_hinge
  #   restore_embs: /app/cache/features/scf_ijb_embs_${subset}.npz
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   features: scf
  #   use_detector_score: True
  #   save_result: "${exp_dir}/${subset}_basic_SVM_det_and_scf_score.npz"
