hydra:
  run:
    dir: ${exp_dir}

#exp_dir: experiments/open_set_uncertainty_small_beta
exp_dir: outputs/experiments/temperature_kappa_${default_kappa}
use_two_galleries: True
recompute_template_pooling: False
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name_unc.yaml
# test_dataset:


test_datasets:
  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: IJBC
    dataset_path: /app/datasets/arcface_ijb/IJBC

  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: IJBB
  #   dataset_path: /app/datasets/arcface_ijb/IJBB
  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set



open_set_identification_metrics:
  # - _target_: evaluation.metrics.FrrFarIdent
  - _target_: evaluation.metrics.DirFar
  # - _target_: evaluation.metrics.F1

fractions: [0, 0.3, 15]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.DirFar

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1



default_kappa: 500
default_beta: 0.5
open_set_identification_methods:

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF_Power
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     logunc: True
  #   pretty_name: "vMF&Power"

  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0
      logunc: False
      T: 1
    pretty_name: "vMF_T-1"


  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0
      logunc: False
      T: 7
    pretty_name: "vMF_T-7"

  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      logunc: False
      T: 1
    pretty_name: "vMF_T-1+SFC"


  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      logunc: True
      T: 1
    pretty_name: "vMF_T-1-log+SFC"

  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      logunc: False
      T: 7
    pretty_name: "vMF_T-7+SFC"


  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0.5
      logunc: True
      T: 7
    pretty_name: "vMF_T-7-log+SFC"

  - embeddings: scf
    template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${default_kappa}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 1
      logunc: False
      T: 1
    pretty_name: "SFC"

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: power
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     logunc: True
  #   pretty_name: "Power"

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0.7
  #     logunc: True
  #   pretty_name: "vMF-log+SFC"


  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: power
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0.7
  #     logunc: True
  #   pretty_name: "power-log+SFC"

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF_Power
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0.7
  #     logunc: True
  #   pretty_name: "vMF&Power-log+SCF"

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF_Power
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 1
  #     logunc: True
  #   pretty_name: "SCF"


  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 1
  #   pretty_name: "SCF"

  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 0
  #   pretty_name: "Be"


  # - embeddings: scf
  #   template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     kappa: ${default_kappa}
  #     beta: ${default_beta}
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 0.7
  #   pretty_name: "Be+SCF"
  