hydra:
  run:
    dir: ${exp_dir}

exp_dir: experiments/paper/filter_curve/${tau_list}
use_two_galleries: False
recompute_template_pooling: True
metric_pretty_name_path: /app/configs/latex_tables/pretty_names/column_pretty_name_unc.yaml
create_pool_plot: False

test_datasets:
  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: ms1m
  #   dataset_path: /app/datasets/ms1m_ident

  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: IJBB
    dataset_path: /app/datasets/arcface_ijb/IJBB

  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: IJBC
    dataset_path: /app/datasets/arcface_ijb/IJBC

  - _target_: evaluation.test_datasets.FaceRecogntioniDataset
    dataset_name: lfw
    dataset_path: /app/datasets/lfw_ident


  # - _target_: evaluation.test_datasets.FaceRecogntioniDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set



open_set_identification_metrics:
  # - _target_: evaluation.metrics.FrrFarIdent
  - _target_: evaluation.metrics.DirFar
  # - _target_: evaluation.metrics.F1

fractions: [0, 0.3, 15]

open_set_identification_uncertainty_metrics:
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.FrrFarIdent
  
  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.DirFar

  # - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
  #   fractions: ${fractions}
  #   metric_to_monitor:
  #     _target_: evaluation.metrics.F1

  - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUnc
    fractions: ${fractions}
    metric_to_monitor:
      _target_: evaluation.metrics.F1_classic



default_beta: 0.5

tau_list: [0.333]

open_set_identification_methods:
  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF #PoolingProb
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${tau_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 1
      aggregation: sum
      T: 5.3757
      T_data_unc: 1
      kappa_is_tau: True
    pretty_name: "SCF"

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF #PoolingProb
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
      class_model: vMF
      kappa: ${tau_list}
      beta: ${default_beta}
      uncertainty_type: maxprob
      alpha: 0
      aggregation: sum
      T: 5.3757
      T_data_unc: 1
      kappa_is_tau: True
    pretty_name: "vMF"


  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF #PoolingProb
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: power
  #     kappa: ${tau_list}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0
  #     aggregation: sum
  #     T: 0.28836
  #     T_data_unc: 1
  #     kappa_is_tau: True
  #   pretty_name: "Power"

  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF #PoolingProb
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: power
  #     kappa: ${tau_list}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0.5
  #     aggregation: sum
  #     T: 0.28836
  #     T_data_unc: 30
  #     kappa_is_tau: True
  #   pretty_name: "Power + SCF"

  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     kappa: ${tau_list}
  #     beta: ${default_beta}
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 0
  #     T: 22.79
  #     T_data_unc: 1
  #     kappa_is_tau: True
  #   pretty_name: Be


  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF #PoolingProb
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.posterior_prob_based.PosteriorProbability
  #     class_model: vMF
  #     kappa: ${tau_list}
  #     beta: ${default_beta}
  #     uncertainty_type: maxprob
  #     alpha: 0.5
  #     aggregation: sum
  #     T: 5.3757
  #     T_data_unc: 30
  #     kappa_is_tau: True
  #   pretty_name: "vMF + SCF"


  # - embeddings: scf
  #   gallery_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   probe_template_pooling_strategy:
  #     _target_: evaluation.template_pooling_strategies.PoolingSCF
  #   use_detector_score: True
  #   sampler:
  #     _target_: evaluation.samplers.VonMisesFisher
  #     num_samples: 0 # set 0 to use mean of distr as one sample
  #   distance_function: 
  #     _target_: evaluation.distance_functions.open_set_identification.CosineSim
  #   recognition_method:
  #     _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
  #     kappa: ${tau_list}
  #     beta: ${default_beta}
  #     acceptance_score: 
  #       _target_: evaluation.confidence_functions.MaxSimilarity_confidence
  #     uncertainty_function:
  #       _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
  #     alpha: 0.5
  #     T: 22.79
  #     T_data_unc: 30
  #     kappa_is_tau: True
  #   pretty_name: Be + SCF

