hydra:
  run:
    dir: ${exp_dir}

exp_dir: outputs/calibration/paper/be
use_two_galleries: False
recompute_template_pooling: True
num_bins: 15
draw_bin_importance: alpha
draw_averages: True
test_datasets:

  - _target_: evaluation.test_datasets.FaceRecogntionDataset
    dataset_name: ms1m
    dataset_path: /app/datasets/ms1m_ident

  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: IJBC
  #   dataset_path: /app/datasets/arcface_ijb/IJBC

  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: IJBB
  #   dataset_path: /app/datasets/arcface_ijb/IJBB
  # - _target_: evaluation.test_datasets.FaceRecogntionDataset
  #   dataset_name: survFace
  #   dataset_path: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

tau_range: [0.1, 0.45, 10]

default_kappa: 400
default_beta: 0.5
train_T: True
iter_num: 500
lr: 10

open_set_identification_methods:

  - embeddings: scf
    gallery_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    probe_template_pooling_strategy:
      _target_: evaluation.template_pooling_strategies.PoolingSCF
    use_detector_score: True
    sampler:
      _target_: evaluation.samplers.VonMisesFisher
      num_samples: 0 # set 0 to use mean of distr as one sample
    distance_function: 
      _target_: evaluation.distance_functions.open_set_identification.CosineSim
    recognition_method:
      _target_: evaluation.open_set_methods.score_function_based.SimilarityBasedPrediction
      kappa: ${default_kappa}
      beta: ${default_beta}
      acceptance_score: 
        _target_: evaluation.confidence_functions.MaxSimilarity_confidence
      uncertainty_function:
        _target_: evaluation.open_set_methods.uncertainty_functions.BernoulliVariance
      alpha: 0
      T: 44
      T_data_unc: 1
      kappa_is_tau: True
    pretty_name: Be