title: "arcface_base"
backbone:
    name: "iresnet50"
    learnable: true
    criterion:
        name: "partial_fc_loss"
head: null
optimizer:
    name: "partial_fc_sgd_default"
scheduler:
    name: "partial_fc_default_scheduler"