title: "iresnet_ms1m_pfe_normalized"
backbone:
    name: "iresnet50_normalized"
    learnable: false
head:
    name: "pfe_head_adjustable"
    in_feat: 25088
    out_feat: 512
    learnable: true
    criterion:
        name: "mlsloss"
        mean: false
optimizer:
    name: "sgd"
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
scheduler:
    name: "multistep_lr"
    milestones: [3, 6, 9]
    gamma: 0.1
dataset:
    name: "ms1m"
    path: "/gpfs/gpfs0/r.karimov/ms1m/"
    batch_size: 64
    num_face_pb: 4
pretrained_backbone: /gpfs/gpfs0/r.karimov/models/backbone/ms1mv3_arcface_r50/backbone.pth
batch_size: 256
num_classes_batch: 4
is_distributed: true
iterations: 2000
epochs: 12
path_list: /gpfs/gpfs0/r.karimov/casia/list_data.txt
in_size: [112, 112]
logging:
    print_freq: 10
    save_freq: 1
evaluation_configs:
    - name: "lfw_dilemma"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/r.karimov/lfw/data_aligned_sphereface_repo"
    - name: "low_high_similarity"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/r.karimov/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/gpfs/gpfs0/r.karimov/lfw/ldmarks.txt"
    - name: "lfw_6000_pairs"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/r.karimov/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/gpfs/gpfs0/r.karimov/lfw/pairs_val_6000.txt"
      N: 6000
      n_folds: 10
