title: "spherenet_base"
backbone:
    name: "spherenet20"
    learnable: true
    criterion:
        name: "angle_loss"
head: null
optimizer:
    name: "sgd"
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
scheduler: null