title: "spherenet_pfe"
backbone:
    name: "spherenet20"
    learnable: true
head:
    name: "pfe_head"
    in_feats: 512
    learnable: true
criterion:
    name: "mlsloss"
    mean: false
optimizer:
    name: "sgd"
    base_lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
