title: "spherenet_base"
backbone:
    name: "spherenet20"
    learnable: true
    criterion:
        name: "angle_loss"
head: null
optimizer:
    name: "sgd"
    lr: 0.001
    weight_decay: 0.0005
    momentum: 0.9
    nesterov: true
scheduler: null
batch_size: 256
num_classes_batch: 4
is_distributed: false
iterations: 1000
epochs: 3
path_list: /gpfs/gpfs0/k.fedyanin/space/casia/list_data.txt
in_size: [112, 96]
pretrained_backbone: false
logging:
    print_freq: 100
    save_freq: 1
evaluation_configs:
    - name: "accuracy_lfw_6000_pairs"
      type: "lfw"
      lfw_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/data_aligned_sphereface_repo"
      lfw_pairs_txt_path: "/gpfs/gpfs0/k.fedyanin/space/lfw/ldmarks.txt"
      N: 6000
      n_folds: 10
