dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/scale/02_sigm_mul_selection/32/checkpoint.pth"
protocol: "ijbc"
protocol_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/IJB-C/protocols/test1"
config_path: "./configs/models/arcface_emb_norm.yaml"
batch_size: 64
distaces_batch_size: 8
uncertainty_strategy: "emb_norm"
uncertainty_mode: "confidence"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
fusion_distance_uncertainty_metrics: ["first_cosine_mean", "mean_cosine_mean", ]
rejected_portions: [0.0, 0.5, 25]
device_id: 0
save_fig_path: "/gpfs/gpfs0/k.fedyanin/space/figures/test"
verbose: True
cached_embeddings: True
equal_uncertainty_enroll: True