checkpoint_path: "/gpfs/gpfs0/k.fedyanin/space/models/scale/01_frozen/01_sigm_mul/checkpoint.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
protocol: "ijbc"
protocol_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/IJB-C/protocols/test1"
config_path: "./configs/scale/01_activation_selection/sigm_mul.yaml"
batch_size: 64
distaces_batch_size: 8
uncertainty_strategy: "magface"
uncertainty_mode: "confidence"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
fusion_distance_uncertainty_metrics: ["first_cosine_mean", "mean_cosine_mean", ]
device_id: 0
save_fig_path: "/gpfs/gpfs0/k.fedyanin/space/figures/test"
verbose: True
cached_embeddings: True
equal_uncertainty_enroll: True