checkpoint_path: "/app/data/sota.pth"
dataset_path: "/app/data/big"
protocol: "ijbc"
protocol_path: "/app/data/test1"
config_path: "./configs/models/iresnet_ms1m_pfe_normalized.yaml"
batch_size: 64
distaces_batch_size: 8
uncertainty_strategy: "head"
uncertainty_mode: "uncertainty"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
rejected_portions: [0.0, 0.5, 250]
fusion_distance_uncertainty_metrics: ["mean_cosine_min", "PFE_cosine_min", ]
device_id: 0
save_fig_path: "./runs/test"
verbose: True
cached_embeddings: True
equal_uncertainty_enroll: True
distance_based_uncertainty: None #["softmax"]