checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/scale/02_sigm_mul_selection/64/checkpoint.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
config_path: "./configs/scale/02_sigm_mul_coef_selection/64.yaml"
protocol: "ijbc"
protocol_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/IJB-C/protocols/test1"
batch_size: 64
uncertainty_strategy: "scale"
distaces_batch_size: 500
uncertainty_mode: "confidence"
FARs: [0.0001, 0.001, 0.01, 0.05, ]
fusion_distance_uncertainty_metrics: ["first_biased-cosine_mean", "first_cosine_mean", "weighted_cosine_mean", ]
rejected_portions: [0.0, 0.5, 250]
device_id: 0
save_fig_path: "/gpfs/gpfs0/k.fedyanin/space/figures/test"
cached_embeddings: True
verbose: True
equal_uncertainty_enroll: True