checkpoint_path: "/gpfs/data/gpfs0/k.fedyanin/space/models/scale/02_sigm_mul_selection/32/checkpoint.pth"
dataset_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/aligned_data_for_fusion/big"
protocol: "ijbc"
protocol_path: "/gpfs/gpfs0/k.fedyanin/space/IJB/IJB-C/protocols/test1"
config_path: "./configs/scale/01_activation_selection/sigm_mul.yaml"
batch_size: 64
distaces_batch_size: 8
uncertainty_strategy: "scale"
uncertainty_mode: "confidence"
FARs: [0.0001, 0.001, 0.05, ]
rejected_portions: [0.0, 0.5, 25]
fusion_distance_uncertainty_metrics: ["softmax_cosine_harmonic-harmonic", "stat-softmax_cosine_harmonic-harmonic", "softmax_cosine_harmonic-harmonic", "stat-softmax_cosine_harmonic-harmonic", "harmonic-harmonic_cosine_harmonic-harmonic", "stat-harmonic-harmonic_cosine_harmonic-harmonic", ]
device_id: 0
save_fig_path: "/gpfs/gpfs0/k.fedyanin/space/figures/test"
verbose: True
cached_embeddings: True

#fusion_distance_uncertainty_metrics: ["argmax_cosine_mean", "first_cosine_mean", "mean_cosine_mean", "softmax_cosine_mean", ]
#fusion_distance_uncertainty_metrics: ["first_cosine_mean", "mean_cosine_mean", "softmax_cosine_mean", "argmax_cosine_mean", "PFE_cosine_mean"]
