"models": "Method"
"false_accept_num" : ["False Accept", "Count $(\\downarrow)$"]
"false_reject_num": ["False Reject", "Count $(\\downarrow)$"]
"false_ident_num": ["False Ident", "Count $(\\downarrow)$"]
"false_ident-reject_num": ["False Reject/Ident", "Count $(\\downarrow)$"]
"error_sum": ["All errors", "Count $(\\downarrow)$"]
"dir": ["DIR", "$(\\uparrow)$"]
"far": ["FAR", " $(\\downarrow)$"]
"f1": ["F1", " $(\\uparrow)$"]
"f1_class": ["$F_1$"] #["$F_1$", " $(\\uparrow)$"]
"FAR=0.005": ["$\\text{FAR}=0.005$"]
"FAR=0.01": ["$\\text{FAR}=0.01$"]
"FAR=0.05": ["$\\text{FAR}=0.05$"]
"FAR=0.1": ["$\\text{FAR}=0.1$"]