models: "Method"
"false_accept_num" : ["False Accept", "Count"]
"false_reject_num": ["False Reject", "Count"]
"false_ident_num": ["False Ident", "Count"]
"false_ident-reject_num": ["False Reject/Ident", "Count"]
"error_sum": ["All errors", "Count"]
"dir": "DIR"
"far": "FAR"
"f1": "F1"