pretty_name: "Расстояние"
final_AUC_1_rank: ["AUC $(\\%)$", "Ранг 1"]
final_top_1_recall_at_far_0.0001: ["TAR@FAR=$10^{-4}$ $(\\%)$", "Ранг 1"]
final_top_1_recall_at_far_0.001: ["TAR@FAR=$10^{-3}$ $(\\%)$", "Ранг 1"]
final_top_1_recall_at_far_1: ["TAR@FAR=$1$ $(\\%)$", "Ранг 1"]
final_AUC_5_rank: ["AUC $(\\%)$", "Ранг 5"]
final_top_5_recall_at_far_0.0001: ["TAR@FAR=$10^{-4}$ $(\\%)$", "Ранг 5"]
final_top_5_recall_at_far_0.001: ["TAR@FAR=$10^{-3}$ $(\\%)$", "Ранг 5"]
final_top_5_recall_at_far_1: ["TAR@FAR=$1$ $(\\%)$", "Ранг 5"]

final_AUC_10_rank: ["AUC $(\\%)$", "Ранг 10"]
final_top_10_recall_at_far_0.0001: ["TAR@FAR=$10^{-4}$ $(\\%)$", "Ранг 10"]
final_top_10_recall_at_far_1: ["TAR@FAR=$1$ $(\\%)$", "Ранг 10"]
final_auc: "AUC"
final_recall_at_far_1e-06: "TAR@FAR=$10^{-6}$ $(\\%)$"
final_recall_at_far_1e-05: "TAR@FAR=$10^{-5}$ $(\\%)$"
final_recall_at_far_0.01: "TAR@FAR=$0.01$ $(\\%)$"
final_recall_at_far_1: "TAR@FAR=$1$ $(\\%)$"

final_cmc_at_rank_1: ["IR $(\\%)$", "Ранг 1"]
final_cmc_at_rank_10 : ["IR $(\\%)$", "Ранг 10"]
final_cmc_at_rank_50 : ["IR $(\\%)$", "Ранг 50"]
final_cmc_at_rank_500 : ["IR $(\\%)$", "Ранг 500"]