pretty_name: "Метод"
final_AUC_1_rank: ["AUC", "Ранг 1"]
final_top_1_recall_at_far_0.0001: ["TAR@FAR=$10^{-4}$", "Ранг 1"]
final_top_1_recall_at_far_1: ["TAR@FAR=$1$", "Ранг 1"]
final_AUC_10_rank: ["AUC", "Ранг 10"]
final_top_10_recall_at_far_0.0001: ["TAR@FAR=$10^{-4}$", "Ранг 10"]
final_top_10_recall_at_far_1: ["TAR@FAR=$1$", "Ранг 10"]