CosineSim: "Косинусный MaxProb"
CosineSim_NAC-k=5: "Кос. NAC, $k=5$"
CosineSim_NAC-k=15: "Кос. NAC, $k=15$"
CosineSim_NAC-k=30: "Кос. NAC, $k=30$"
CosineSim_NAC-k=60: "Кос. NAC, $k=60$"
CosineSim_NAC-k=120: "Кос. NAC, $k=120$"
CosineSim_NAC-k=240: "Кос. NAC, $k=240$"
CosineSim_NAC-k=480: "Кос. NAC, $k=480$"
CosineSim_NAC-k=1000: "Кос. NAC, $k=1000$"