"vMF": "vMF" 
"vMF+SFC": "vMF+SFC" 
"SCF": "SCF" 
"Be": "Be" 
"Be+SCF": "Be+SCF" 
"vMF-log+SFC": "vMF-log+SFC"

$u_{SCF}$: "$u_{\\text{SCF}}$"
$u_{vMF}$: "$u_{\\text{vMF}}$"
$u_{power}$: "$u_{\\text{power}}$"
$u_{baseline}$: "$u_{\\text{baseline}}$"
$u_{vMF} + u_{SCF}$: "$u_{\\text{vMF}}+u_{\\text{SCF}}$"
$u_{power} + u_{SCF}$: "$u_{\\text{power}}+u_{\\text{SCF}}$"
$u_{baseline} + u_{SCF}$: "$u_{\\text{baseline}}+u_{\\text{SCF}}$"