CosineSim: "Консинусное"
SCF_k_shift_0: "SCF, $k=0$"
SCF_k_shift_10: "SCF, $k=10$" 
SCF_k_shift_150: "SCF, $k=150$" 
SCF_k_shift_300: "SCF, $k=300$" 
SCF_k_shift_600: "SCF, $k=600$" 
SCF_k_shift_1200: "SCF, $k=1200$" 
SCF_k_shift_10000: "SCF, $k=10000$" 
SCF_k_shift_50000: "SCF, $k=50000$" 