batch_size: 36
image_size:
- 528
- 528
max_epochs: 30
model_name: tf_efficientnet_b6_ns
out_indices:
- 3
- 4
n_splits: -1
pseudo_label: pseudo_labels/round2.csv
pseudo_conf_threshold: 0.6
warmup_steps_ratio: 0.1
