GPR_linear_with_cat_kernel: "GPR"
OLS: "OLS"
CatBoost: "CatBoost"
ARIMA: ARIMA
Surr1_linear_kernel: "Surr I OLS"
Surr2_linear_kernel: "Surr II OLS"
Surr3_linear_kernel: "Surr III OLS"
Surr4_linear_kernel: "Surr IV OLS"
surr-ind_base-OLS_linear-kernel_C-0.7_frac-1: "Surr ind. OLS"
surr-ind_base-OLS_RBF-kernel_C-0.1_frac-0.1: "Surr ind. OLS RBF kernel"
surr-ind_base-arbased_linear-kernel_C-0.7_frac-1: "Surr ind. BSAP"
surr-ind_base-ARIMA_linear-kernel_C-0.7_frac-1: "Surr ind. ARIMA"
surr-ind_base-CatBoost_linear-kernel_C-0.7_frac-1: "Surr ind. CatBoost"

"Surr1_linear_kernel_ARIMA": "Surr I ARIMA"
"Surr2_linear_kernel_ARIMA": "Surr II ARIMA"
"Surr3_linear_kernel_ARIMA": "Surr III ARIMA"
"Surr4_linear_kernel_ARIMA": "Surr IV ARIMA"

"Surr1_linear_kernel_CatBoost": "Surr I CatBoost"
"Surr2_linear_kernel_CatBoost": "Surr II CatBoost"
"Surr3_linear_kernel_CatBoost": "Surr III CatBoost"
"Surr4_linear_kernel_CatBoost": "Surr IV CatBoost"

Naive_OLS: "Naive BS OLS"
Naive_ARIMA: "Naive BS ARIMA"
Naive_CatBoost: "Naive BS CatBoost"
MEB_OLS: "MEB BS OLS"
MEB_ARIMA: "MEB BS ARIMA"
MEB_CatBoost: "MEB BS CatBoost"
SBB_OLS: "SBB BS OLS"
SBB_ARIMA: "SBB BS ARIMA"
SBB_CatBoost: "SBB BS CatBoost"
BSAP_OLS: "BSAP BS OLS"
BSAP_ARIMA: "BSAP BS ARIMA"
BSAP_CatBoost: "BSAP BS CatBoost"