seed_everything: 777
trainer:
#   logger:
#     class_path: pytorch_lightning.loggers.WandbLogger
#     init_args:
#       project: "scf-uniform-batch_from_start"
  log_every_n_steps: 3
  default_root_dir: outputs/scf_train
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      every_n_epochs: 1
      dirpath: outputs/scf_uniform_batch/default_scf
      save_last: True
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args: 
      logging_interval: "step"
  - class_path: face_lib.models.scf.Prediction_writer
    init_args: 
      output_dir: /app/datasets/arcface_ijb/IJBC/embeddings
      file_name: uniform_scf_embs_IJBC
      write_interval: epoch
  max_epochs: 16
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
model:
    class_path: face_lib.models.scf.SphereConfidenceFace
    init_args:
        backbone:
            class_path: face_lib.models.lightning_wrappers.ResNet
            init_args:
                resnet_name: iresnet50_normalized
                weights: /app/model_weights/backbone/ms1mv3_arcface_r50/backbone.pth
                learnable: False
        head:
            class_path: face_lib.models.heads.SCFHead
            init_args:
                convf_dim: 25088
                latent_vector_size: 2048 #8096
        scf_loss:
            class_path: face_lib.models.losses.KLDiracVMF
            init_args:
                z_dim: 512
                radius: 64
        softmax_weights:
            class_path: face_lib.models.scf.SoftmaxWeights
            init_args:
                softmax_weights_path: /app/model_weights/backbone/ms1mv3_arcface_r50/softmax_weight.pt
                radius: 64 #${model.scf_loss.init_args.radius}
        optimizer_params:
            optimizer_path: torch.optim
            optimizer_name: AdamW # Adam
            params:
                lr: 3e-5
                weight_decay: 5e-4
        scheduler_params:
            scheduler: StepLR
            params:
                step_size: 2
                gamma: 0.5
            interval: "step"
            frequency: 1
        permute_batch: False
        validation_dataset:
            class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
            init_args:
                dataset_path: /app/datasets/arcface_ijb/IJBC
                dataset_name: IJBC
                norm_image: True
        template_pooling_strategy:
            class_path: evaluation.template_pooling_strategies.PoolingConcentration
        recognition_method:
            class_path: evaluation.verification_methods.distance_based_verification.VerifEval
            init_args:
                distance_function:
                    class_path: evaluation.distance_functions.distance_functions.CosineSimPairwise
        verification_metrics:
            - _target_: evaluation.metrics.TarFar
              far_range: [-6, -0.5, 0.1]
              display_fars: [1e-6, 1e-5, 1e-4, 1e-3]

data:
    class_path: face_lib.dataset_classes.lightning_datasets.UncertaintyDataModule
    init_args:
        train_dataset:
            class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
            init_args:
                root_dir: /app/datasets/ms1m/
        validation_dataset:
            class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
            init_args:
                dataset_path: /app/datasets/arcface_ijb/IJBC
                dataset_name: IJBC
                norm_image: True
        train_batch_sampler:
            class_path: face_lib.dataset_classes.samplers.UniformBatchSamplerWithBins
            init_args:
                cosine_sim_path: /app/model_weights/ms1m_cache/cosine_sim.npy
                batch_size: 400
                cosine_border_values: [0.5, 0.6, 0.7, 0.8, 1]
        # train_batch_sampler:
        #     class_path: face_lib.dataset_classes.samplers.UniformBatchSampler
        #     init_args:
        #         cosine_sim_path: /app/model_weights/ms1m_cache/cosine_sim.npy
        #         batch_size: 400
        batch_size: 400
        num_workers: 40

        # predict_dataset:
        #     class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
        #     init_args:
        #         root_dir: /app/datasets/ms1m/

        predict_dataset:
            class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
            init_args:
                dataset_path: /app/datasets/arcface_ijb/IJBC
                dataset_name: IJBC
                norm_image: True
# predict_dataset:
#     class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
#     init_args: 
#         root_dir: /app/datasets/ms1m/
#         test: True
#         num_classes: 3531
# predict_dataset:
#     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
#     init_args:
#         dataset_path: /app/datasets/gaussian_nose
#         dataset_name: nose
#         norm_image: True
# predict_dataset:
#     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
#     init_args:
#         dataset_path: /app/datasets/interpolation
#         dataset_name: inter
#         norm_image: True
# predict_dataset:
#     class_path: face_lib.dataset_classes.lfw.LFW_aligned_images
#     init_args:
#         dataset_path: /app/datasets/lfw/data_aligned_112_112
        #norm_image: True
# predict_dataset:
#     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
#     init_args:
#         dataset_path: /app/datasets/arcface_ijb/IJBB
#         dataset_name: IJBB
#         norm_image: True
