seed_everything: 7
trainer:
#   logger:
#     class_path: pytorch_lightning.loggers.WandbLogger
#     init_args:
#       project: "whale_scf_uncertainty_train"
  log_every_n_steps: 3
  default_root_dir: outputs/scf_train
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      every_n_train_steps: 1000
      dirpath: outputs/scf_train/weights_whale_v2
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args: 
      logging_interval: "step"
  - class_path: face_lib.models.scf.Prediction_writer
    init_args: 
      output_dir: /app/cache/features
      file_name: scf_embs_whale # scf_embs_inter  #scf_embs_lfw #scf_embs_ms1m_3531-classes_0-seed_30-min-class-size
      write_interval: epoch
  max_epochs: 6
  accelerator: gpu
  devices: 1
model:
    class_path: face_lib.models.scf.SphereConfidenceFace
    init_args:
        backbone:
            class_path: face_lib.models.lightning_wrappers.EfficientNet
            init_args:
                checkpoint_path: "/app/sandbox/happy_whale/kaggle-happywhale-1st-place/result/b6_bottleneck_feature_fix_nb/1/last-v4.ckpt"
                learnable: False
        head:
            class_path: face_lib.models.heads.SCFHead
            init_args:
                convf_dim: 776
                latent_vector_size: 4096
        scf_loss:
            class_path: face_lib.models.losses.KLDiracVMF
            init_args:
                z_dim: 512
                radius: 64
        optimizer_params:
            optimizer_path: torch.optim
            optimizer_name: AdamW # Adam
            params:
                lr: 5e-5
                weight_decay: 5e-3
        scheduler_params:
            scheduler: StepLR
            params:
                step_size: 1
                gamma: 0.5
            # interval: "step"
            # frequency: 1
        permute_batch: False



data:
    class_path: face_lib.dataset_classes.lightning_datasets.UncertaintyDataModule
    init_args:
        train_dataset:
            class_path: face_lib.dataset_classes.lightning_datasets.WhaleDataset
            init_args:
                config_path: /app/sandbox/happy_whale/kaggle-happywhale-1st-place/config/efficientnet_b6_new.yaml
                image_dir: /app/sandbox/happy_whale/kaggle-happywhale-1st-place/input
        predict_dataset:
            class_path: face_lib.dataset_classes.lightning_datasets.WhaleDataset
            init_args:
                config_path: /app/sandbox/happy_whale/kaggle-happywhale-1st-place/config/efficientnet_b6_new.yaml
                image_dir: /app/sandbox/happy_whale/kaggle-happywhale-1st-place/input
                test: True
        batch_size:  16
        num_workers: 10

        # train_dataset:
        #     class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
        #     init_args:
        #         root_dir: /app/datasets/ms1m/
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
        #     init_args: 
        #         root_dir: /app/datasets/ms1m/
        #         test: True
        #         num_classes: 3531
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/gaussian_nose
        #         dataset_name: nose
        #         norm_image: True
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/interpolation
        #         dataset_name: inter
        #         norm_image: True
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.lfw.LFW_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/lfw/data_aligned_112_112
                #norm_image: True
        # predict_dataset:
        #     class_path: face_lib.datasets.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/arcface_ijb/IJBC
        #         dataset_name: IJBC
        #         norm_image: True


        # predict_dataset:
        #     class_path: face_lib.datasets.qmul.SurvFace
        #     init_args:
        #         data_dir: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set


