

seed_everything: 7
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: "face_incertainty_train"
  log_every_n_steps: 3
  default_root_dir: outputs/pfe_train
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      every_n_train_steps: 5000
      dirpath: outputs/pfe_train/weights
  - class_path: face_lib.models.pfe.IJB_writer
    init_args: 
      output_dir: /app/cache/features
      subset: ${data.init_args.data_predict_subset}
      write_interval: epoch
  max_epochs: 4
  accelerator: gpu
  devices: 2
model:
    class_path: face_lib.models.pfe.ProbabilisticFaceEmbedding
    init_args:
        weights: None # /app/model_weights/pfe_old/sota.pth
        head_args:
          in_feat: 25088
          out_feat: 512
          learnable: True
        pfe_loss:
            class_path: face_lib.models.losses.PFELoss
            init_args:
              mean: True
        optimizer_params:
            optimizer_path: face_lib.optimizers.lars
            optimizer_name: LARS
            params:
                lr: 0.01
                weight_decay: 1e-5
        scheduler_params:
            scheduler: StepLR
            params:
                step_size: 10000
                gamma: 0.5
            interval: "step"
            frequency: 1


data:
    class_path: face_lib.datasets.lightning_datasets.UncertaintyDataModule
    init_args:
        data_train_dir: /app/datasets/ms1m/
        add_nose: False
        data_predict_dir: /app/datasets/arcface_ijb
        data_predict_subset: IJBC
        batch_size: 200
        num_workers: 20

