
seed_everything: 777
mode: predict
weights_path: /app/outputs/scf_multiple/scf_base/last-v3.ckpt
trainer:
  _target_: pytorch_lightning.Trainer
  callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint 
    every_n_epochs: 1
    dirpath: outputs/scf_multiple/scf_base
    save_last: True
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "step"
  - _target_: face_lib.models.scf.Prediction_writer
    output_dir: /app/datasets/arcface_ijb/IJBC/embeddings
    file_name: scf_layer1_2_epoch_embs_IJBC
    write_interval: epoch
  max_epochs: 2
  accelerator: gpu
  devices: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 3
  default_root_dir: outputs/scf_train
  val_check_interval: 0.1
  enable_checkpointing: true
model:
    _target_: face_lib.models.scf.SphereConfidenceFace
    backbone:
        _target_: face_lib.models.lightning_wrappers.ResNet
        resnet_name: iresnet50_normalized
        weights: /app/model_weights/backbone/ms1mv3_arcface_r50/backbone.pth
        learnable: False
    # head:
    #     _target_: face_lib.models.heads.SCFHead
    #     convf_dim: 25088
    #     latent_vector_size: 4096
    head:
        _target_: face_lib.models.heads.SCFHeadLayer1
        num_planes: [32, 32, 32, 32]
        num_layers: [1, 2, 3, 4]
    scf_loss:
        _target_: face_lib.models.losses.KLDiracVMF
        z_dim: 512
        radius: 64
    softmax_weights:
        _target_: face_lib.models.scf.SoftmaxWeights
        softmax_weights_path: "/app/model_weights/backbone/ms1mv3_arcface_r50/softmax_weight.pt"
        radius: 64
    optimizer_params:
        optimizer_path: torch.optim
        optimizer_name: AdamW
        params:
            lr: 3e-2 #3e-5
            weight_decay: 5e-4
    scheduler_params:
            # scheduler: StepLR
            # params:
            #     step_size: 2
            #     gamma: 0.1
        scheduler: OneCycleLR
        params:
            max_lr: 3e-4
            steps_per_epoch: 13863
            epochs: 2
            div_factor: 1e1
            final_div_factor: 1e2
        interval: step
    validation_dataset:
        _target_: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: True
    template_pooling_strategy:
        _target_: evaluation.template_pooling_strategies.PoolingConcentration
    recognition_method:
        _target_: evaluation.verification_methods.distance_based_verification.VerifEval
        distance_function:
            _target_: evaluation.distance_functions.distance_functions.CosineSimPairwise
    permute_batch: False
    verification_metrics:
        - _target_: evaluation.metrics.TarFar
          far_range: [-5, -0.5, 0.1]
          display_fars: [1e-5, 1e-4, 1e-3, 1e-2]
    verification_uncertainty_metrics:
        - _target_: evaluation.uncertainty_metrics.DisposeBasedOnUncVerif
          fractions: [0, 0.5, 10]
          metric_to_monitor:
            _target_: evaluation.metrics.TarFar
            far_range: [-5, -0.5, 0.1]
            display_fars: [1e-5, 1e-4, 1e-3, 1e-2]

data:
    _target_: face_lib.dataset_classes.lightning_datasets.UncertaintyDataModule
    train_dataset:
        _target_: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
        root_dir: /app/datasets/ms1m/
    validation_dataset:
        _target_: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: True

    predict_dataset:
        _target_: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        dataset_path: /app/datasets/arcface_ijb/IJBC
        dataset_name: IJBC
        norm_image: True
    batch_size: 50
    num_workers: 38